docs: Add RedwoodJS Quick Start
defer-run/documentation pull request #3
Opened 2023-07-14 13:32 UTC by dthyresson

This PR is the first draft of a Defer quick start with RedwoodJS.

Note that since I cannot run the Nextra docs, I haven't checked the layout etc.

I expect some tweaks to the docs once I have other RedwoodJS Core team members test them out and give feedback.

This PR also includes a few small changes to the `syncContacts` examples for other integrations.

2023-07-14 15:01 UTC, charlypoly requested changes
@dthyresson did some minor UI and typos fixes  🦅 

Thank you very much for putting this guide down! 🙇🏼

2023-07-14 15:01 UTC, charlypoly commented on pages/quickstart/redwoodjs.mdx
> +
```suggestion
.
├── api
│   ├── db/
│   ├── package.json
│   ├── server.config.js
│   ├── src/
│   │   ├── directives/
│   │   ├── functions/
│   │   │   ├── runHelloWorld/
│   │   │   │   └── runHelloWorld.ts <- API endpoint to invoke job
│   │   ├── graphql/
│   │   ├── jobs/ <- Create a new Jobs folder
│   │   │   ├── clients
│   │   │   │   └── defer.ts <- Configure and export the defer client
│   │   │   └── defer/ <- Write your defer background, cron, delayed, and workflow functions here
│   │   │       └── helloWorld.ts
│   │   ├── lib/
│   │   │   └── logger.ts
│   │   └── services/
├── package.json
├── redwood.toml
├── web/
```

2023-07-14 15:01 UTC, charlypoly commented on pages/quickstart/redwoodjs.mdx
> +```txt {4}
```suggestion
```txt {10, 12, 14, 15}
```

2023-07-14 15:01 UTC, charlypoly commented on pages/quickstart/redwoodjs.mdx
> +Then, open your browser and visit the `http://localhost:8910/.redwood/functions/hellow?name=Charly` function endpoint.
```suggestion
Then, open your browser and visit the `http://localhost:8910/.redwood/functions/helloWorld?name=Charly` function endpoint.
```

Is it a typo or am I missing something? 👀

2023-07-14 15:01 UTC, charlypoly commented on pages/quickstart/redwoodjs.mdx
> +If you are wondering how calling a background function triggers an execution on Defer Platform, please refer to this guide: [How Defer works](/platform/how-defer-works).
```suggestion
```

Move in the dedicated lonely `<Callout>` below

2023-07-14 15:01 UTC, charlypoly commented on pages/quickstart/redwoodjs.mdx
> +
```suggestion

If you are wondering how calling a background function triggers an execution on Defer Platform, please refer to this guide: [How Defer works](/platform/how-defer-works).
```

2023-07-14 15:01 UTC, charlypoly commented on pages/quickstart/redwoodjs.mdx
> +**
```suggestion
**A Defer application needs a successful build to accept executions**

```

2023-07-14 15:01 UTC, charlypoly commented on pages/quickstart/redwoodjs.mdx
> +### Configure your API deployment
```suggestion
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

### Configure your API deployment
```

2023-07-14 15:02 UTC, charlypoly commented on pages/quickstart/redwoodjs.mdx
> +
I updated it to be aligned with other guides

2023-07-14 15:12 UTC, dthyresson commented on pages/quickstart/redwoodjs.mdx
> +Then, open your browser and visit the `http://localhost:8910/.redwood/functions/hellow?name=Charly` function endpoint.
Typo, bad copy pasting on my side. Thanks!

2023-07-14 15:14 UTC, dthyresson commented
> @dthyresson did some minor UI and typos fixes 🦅
> 
> Thank you very much for putting this guide down! 🙇🏼

Thanks for the typo fixes and formatting ... it's tough to write mdx blindly without the actual render :)

I believe I committed all the suggestions.

2023-07-17 09:08 UTC, charlypoly approved these changes

2023-07-19 13:18 UTC, charlypoly commented
@dthyresson are we still waiting for reviews from the RedwoodJS Core team? 👀

2023-07-19 16:45 UTC, dthyresson commented
> @dthyresson are we still waiting for reviews from the RedwoodJS Core team? 👀

Yes. Thanks for reminding me. I’ve asked someone for a review today/tomorrow

2023-07-23 17:43 UTC, charlypoly commented
@dthyresson, is `yarn rw generate function helloWorld` gonna be the real command or is it gonna be behind the `experimental` command as follows: `yarn rw experimental defer function helloWorld`?

2023-07-25 13:57 UTC, dthyresson commented
> @dthyresson, do you already know which command will be defined to generate a defer background function? (`yarn rw experimental defer function`)
> 
> Asking for the upcoming Partner pitch 🚀

Finished Core team review and good to publish. 👍 

At moment there will not be a dedicated defer command to generate a type of function as I haven't had a chance to work on it.

We plan on moving much out of experimental (like the inngest ones) and at that time can add defer function setup and generators, if that's ok?

It would be similar to: https://github.com/inngest/envelop-plugin-inngest/tree/main/packages/setup/redwoodjs for the functions -- but a little different for the sdk setups.

For the partner pitch you can mention in future RW will have setup and generator commands.

2023-07-26 09:30 UTC, merged